In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [2]:
df=pd.read_csv ('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.drop(['Unnamed: 32','id'],axis=1,inplace=True)

In [4]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [5]:
df.shape

(569, 31)

## Train test split

In [6]:
X_train,X_test,y_train,y_test =train_test_split(df.iloc[:,1:],df.iloc[:,:1],test_size=0.2)

In [7]:
scalar=StandardScaler()
X_train=scalar.fit_transform(X_train)
X_test=scalar.transform(X_test)

In [8]:
X_train

array([[ 1.43818131,  0.73611131,  1.46325406, ...,  0.82972158,
         0.45997916,  0.44304007],
       [ 0.03445135,  0.88104417,  0.10452819, ...,  0.92557381,
         3.64192143,  3.33317958],
       [ 0.03445135,  1.96919091,  0.02988644, ..., -0.49738253,
        -1.64142518, -0.34307346],
       ...,
       [-1.53597156, -1.11350809, -1.53389917, ..., -1.72833487,
        -0.50927948, -0.31438722],
       [-1.31946885, -0.22320622, -1.31243465, ..., -0.97170131,
        -0.73183804, -0.15550953],
       [-0.31365105, -1.16411957, -0.31748476, ..., -0.85218556,
        -0.76731839,  0.92243141]])

In [9]:
y_train


diagnosis
198         M
190         M
238         B
41          M
11          M
..        ...
30          M
46          B
175         B
359         B
336         B

[455 rows x 1 columns]

In [10]:
encoder= LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

/home/section/sandman_venv/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/section/sandman_venv/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


In [11]:
y_train

array([1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,

## Numpy array to Pytorch tensor

In [12]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [13]:
X_train_tensor.shape


torch.Size([455, 30])

In [14]:
X_train_tensor

tensor([[ 1.4382,  0.7361,  1.4633,  ...,  0.8297,  0.4600,  0.4430],
        [ 0.0345,  0.8810,  0.1045,  ...,  0.9256,  3.6419,  3.3332],
        [ 0.0345,  1.9692,  0.0299,  ..., -0.4974, -1.6414, -0.3431],
        ...,
        [-1.5360, -1.1135, -1.5339,  ..., -1.7283, -0.5093, -0.3144],
        [-1.3195, -0.2232, -1.3124,  ..., -0.9717, -0.7318, -0.1555],
        [-0.3137, -1.1641, -0.3175,  ..., -0.8522, -0.7673,  0.9224]],
       dtype=torch.float64)

In [16]:
X_train_tensor.shape

torch.Size([455, 30])

#Defining Model

In [35]:
class MySimpleNN():
    def __init__(self,X):
        self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)
    def forward(self,X):
        z=torch.matmul(X,self.weights) + self.bias
        y_pred=torch.sigmoid(z)
        return(y_pred)
    def loss_function (self,y_pred,y):

        #Clamp predictions to avoind log 0
        epsilon=1e-7

        y_pred=torch.clamp(y_pred,epsilon,1-epsilon)

        #Calculate Loss
        loss= -(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
        return loss
        

In [40]:
#importtant parameters
learning_rate=0.1
epochs=50

In [41]:
#Training Pipeline

model= MySimpleNN(X_train)

#Run loops
 
for epoch in range(epochs):

    #Forward pass
    y_pred=model.forward(X_train_tensor)
    # print(y_pred)

    #Calculate loss
    loss = model.loss_function(y_pred,y_train_tensor)
    
    #backward pass

    loss.backward()


    # updates weights 
    with torch.no_grad():
         model.weights-=learning_rate*model.weights.grad
         model.bias-=learning_rate*model.bias.grad
    
    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    #print loss in each epoch
    print(f'Epoch: {epoch+1 }, Loss: {loss.item()}')


Epoch: 1, Loss: 3.7891225321670405
Epoch: 2, Loss: 3.667439018861448
Epoch: 3, Loss: 3.5382067029926914
Epoch: 4, Loss: 3.4057371799495892
Epoch: 5, Loss: 3.27106986969332
Epoch: 6, Loss: 3.1360815637773545
Epoch: 7, Loss: 2.9982986251809187
Epoch: 8, Loss: 2.8558649976237485
Epoch: 9, Loss: 2.7069042941575456
Epoch: 10, Loss: 2.554786496187359
Epoch: 11, Loss: 2.4043022009948873
Epoch: 12, Loss: 2.252000074204404
Epoch: 13, Loss: 2.1003107588222196
Epoch: 14, Loss: 1.9504692323122002
Epoch: 15, Loss: 1.8039616195609731
Epoch: 16, Loss: 1.6653593268225229
Epoch: 17, Loss: 1.5325163835572804
Epoch: 18, Loss: 1.408647182957754
Epoch: 19, Loss: 1.2946803368444921
Epoch: 20, Loss: 1.1948325059945233
Epoch: 21, Loss: 1.109546922361455
Epoch: 22, Loss: 1.0386191347844604
Epoch: 23, Loss: 0.9810953088684322
Epoch: 24, Loss: 0.9353677505341148
Epoch: 25, Loss: 0.8994154402375902
Epoch: 26, Loss: 0.8711040552008852
Epoch: 27, Loss: 0.848495885743949
Epoch: 28, Loss: 0.8300510775800227
Epoch: 29

In [42]:
model.bias


tensor([-0.2777], dtype=torch.float64, requires_grad=True)

In [43]:
model.weights

tensor([[ 0.2339],
        [ 0.4065],
        [ 0.0992],
        [ 0.4051],
        [ 0.2441],
        [-0.1880],
        [-0.4759],
        [-0.0980],
        [ 0.1422],
        [-0.0520],
        [-0.2456],
        [ 0.0152],
        [ 0.1928],
        [ 0.2636],
        [ 0.0873],
        [ 0.2546],
        [-0.2334],
        [-0.2458],
        [ 0.2629],
        [-0.0229],
        [-0.3588],
        [-0.2720],
        [-0.1921],
        [ 0.0437],
        [-0.0680],
        [ 0.0742],
        [-0.1336],
        [ 0.2655],
        [-0.1660],
        [ 0.3308]], dtype=torch.float64, requires_grad=True)

In [47]:
#Evaluation

with torch.no_grad():
    y_pred=model.forward(X_test_tensor)
    y_pred=(y_pred>0.5).float()
    accuracy=(y_pred==y_test_tensor).float().mean()
print(f'Accuracy : {accuracy.item()}')
# print(y_pred)

Accuracy : 0.5906432867050171
